version: '3.1'

services:

  php:
    image: php:8.2-apache
    container_name: php82
    ports: 
      - 8000:80
    volumes:
      - ./public:/var/www/html
    
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example


